### ISSUE TITLE
Default arguments cause issues in separate compilation

### ISSUE THREAD

**Issue by OlegYch** [sbt/zinc#559]
https://github.com/OlegYch/sbt-zinc-559
adding or removing fields from nested class is not always picked by dependent classes
note that sometimes it's only test classes that fail to be recompiled, sometimes it's a class in the same project

**Comment by eed3si9n** [comment]
Thanks for the report! Would you like to try sending a PR for this?
I am guessing that the relevant code base would be similar to the PR I sent a while back https://github.com/sbt/zinc/pull/424

**Comment by OlegYch** [comment]
i'll try to take a look

**Comment by jvican** [comment]
Thanks for this reproduction @OlegYch, I'll try to have a look. In the meanwhile, reproducing this in scripted would definitely say if this is an issue with latest master. I would appreciate such a contribution.

**Comment by OlegYch** [comment]
@jvican i have a bunch of failing tests on master
```
[error] Failed tests:
[error]         sbt.inc.MultiProjectIncrementalSpec
[error]         sbt.inc.NameHashingCompilerSpec
[error]         sbt.inc.cached.CachedHashingSpec
[error]         sbt.inc.ClasspathHashingHookSpec
[error]         sbt.inc.IncrementalCompilerSpec
[error]         sbt.inc.BinaryDepSpec
[error]         sbt.inc.NestedJavaClassSpec
[error]         sbt.inc.ClassFileManagerHookSpec
[error] Error during tests:
[error]         sbt.inc.cached.ProjectRebaseCacheSpec
[error]         sbt.inc.cached.ExportedCacheSpec
```
with errors like
```
[info] - should recompile sealed classes correctly *** FAILED ***
[info]   sbt.internal.inc.InvalidComponent: The compiler bridge sources org.scala-sbt:compiler-bridge_2.12:1.2.1-SNAPSHOT:compile could not be retrieved.
[info]
[info]  Note: Unresolved dependencies path:
[info]          org.scala-sbt:compiler-bridge_2.12:1.2.1-SNAPSHOT
[info]            +- org.scala-sbt.temp:temp-module-98ec89c315ed408f615fff2c4774286d17323b01:1.2.1-SNAPSHOT
[info]   at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:272)
```
any idea what that means?
i'm on windows btw and need to workaround https://github.com/sbt/contraband/issues/122 and https://github.com/scalapb/ScalaPB/issues/268 before i can contribute

**Comment by jvican** [comment]
Oh man sorry about that. To remove those errors you need to run ‘publishBridges’

**Comment by OlegYch** [comment]
@jvican thanks that works

**Comment by jvican** [comment]
@OlegYch did you succeed in reproducing this with latest master? :smile:

**Comment by OlegYch** [comment]
@jvican sorry haven't got time yet, i'll try later today

**Comment by OlegYch** [comment]
@jvican i added a test here https://github.com/OlegYch/zinc/commit/3d8084f84f887bdfb86dbb158d84b748cda27334 but it doesn't fail
not sure if it was fixed or i'm not using scripted correctly...

**Comment by OlegYch** [comment]
oh wait it actually does fail with a bit more steps

**Comment by jvican** [comment]
Excellent, I’ll have a look at it soon!

**Comment by jvican** [comment]
Thank you for the reproduction @OlegYch, this is an issue I ran into in bloop and could not reproduce a few weeks ago, and you successfully found the way to reproduce it. [I've simplified your test case in your PR](
https://github.com/scalacenter/zinc/commit/4da5c7d623675b7441ee07462687952e1607204b) and will be merging it soon.
  
The issue at hand is solely related to the handling of default arguments in the compiler. The reason why this fails is because when the compiler compiles the second iteration (after moving `a2.scala` to `a.scala`), the compiler's class file parser does not correctly set the `associateFile` field of the nested class `Foo.Bar` in the intricate scenario where:
  
1. We're unpickling a class (`Bar`) nested in a module (`Foo`), and
2. That same class uses default arguments somewhere in its API (in this case in the constructor, but moving that to a method does not change anything).
  
From what my experiments tell, if any of those conditions are not met, the test compiler sets the associated file of `Foo` and `Bar`. I'm looping in @lrytz as this is a bug in the compiler and he may understand better what is going on here and how to fix it (Lukas: note that `Foo.Bar.isSynthetic` is also true).
  
This is the issue, but we can work around it in Zinc while a fix makes it into upstream. More details in the upcoming PR.

**Comment by jvican** [comment]
Fixed in https://github.com/sbt/zinc/pull/591

**Comment by OlegYch** [comment]
@jvican i'm running sbt 1.3.0-RC1 now, but still see this problem in https://github.com/OlegYch/sbt-zinc-559

**Comment by jvican** [comment]
I cannot reproduce with Bloop 1.3.0-RC1, so it's most likely a bug in sbt or the right commit was not included in the version.

**Comment by OlegYch** [comment]
@jvican how do you run things with bloop?

**Comment by OlegYch** [comment]
@jvican i get the same error with bloop 1.3.0
```
olegych@DESKTOP-EKE9IQD:/mnt/d/Distrib/Coding/java/scala/sbt-zinc-559$ ~/.bloop/bloop run root-test
Compiling root (1 Scala source)
Compiled root (375ms)
Compiling root (1 Scala source)
Compiled root (329ms)
[E] Exception in thread "main" java.lang.NoSuchMethodError: qwe.BuyOrderData2$Filter$.$lessinit$greater$default$3()I
[E]     at qwe.BuyOrderDataImplTest$.delayedEndpoint$qwe$BuyOrderDataImplTest$1(test.scala:6)
[E]     at qwe.BuyOrderDataImplTest$delayedInit$body.apply(test.scala:3)
[E]     at scala.Function0.apply$mcV$sp(Function0.scala:34)
[E]     at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[E]     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[E]     at scala.App.$anonfun$main$1$adapted(App.scala:76)
[E]     at scala.collection.immutable.List.foreach(List.scala:389)
[E]     at scala.App.main(App.scala:76)
[E]     at scala.App.main$(App.scala:74)
[E]     at qwe.BuyOrderDataImplTest$.main(test.scala:3)
[E]     at qwe.BuyOrderDataImplTest.main(test.scala)
```

**Comment by OlegYch** [comment]
hm it says `bloop 1.3.0-RC1` even though i installed it from `https://github.com/scalacenter/bloop/releases/download/v1.3.0/install.py`

**Comment by jvican** [comment]
I'm looking into why this is not yet fixed tomorrow, thanks for reporting @OlegYch :pray:

**Comment by OlegYch** [comment]
@jvican any luck?

**Comment by jvican** [comment]
No sorry, won’t be able to have a look at this any time soon

**Comment by alexdupre** [comment]
Not unexpected, but sbt 1.3.0 was released with this bug.

**Comment by OlegYch** [comment]
i can't reproduce this with scala 2.13, so i guess it was fixed there?

**Comment by eed3si9n** [comment]
We've always suspected that the bug was coming from Scala, so I am not surprised that it's fixed there.

**Comment by OlegYch** [comment]
i'm closing this then since whatever was the fix it's unlikely to be backported on 2.12

**Comment by retronym** [comment]
2.12.x backport of a 2.13.x fix to associated file https://github.com/scala/scala/pull/8889
