### ISSUE TITLE
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

### ISSUE THREAD

**Issue by theangrydev** [sbt/zinc#641]
Using Gradle 5.2.1 and zinc 'com.typesafe.zinc:zinc:0.3.15' I see:

```
> Task :compileTestScala FAILED
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
        at scala.tools.nsc.Driver.process(Driver.scala:51)
        at scala.tools.nsc.Main.process(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.compiler.RawCompiler.apply(RawCompiler.scala:33)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:159)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:155)
        at sbt.IO$.withTemporaryDirectory(IO.scala:358)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:155)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:152)
        at sbt.IO$.withTemporaryDirectory(IO.scala:358)
        at sbt.compiler.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:152)
        at sbt.compiler.IC$.compileInterfaceJar(IncrementalCompiler.scala:58)
        at sbt.compiler.IC.compileInterfaceJar(IncrementalCompiler.scala)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.getCompilerInterface(ZincScalaCompilerFactory.java:120)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.access$200(ZincScalaCompilerFactory.java:49)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$2.apply(ZincScalaCompilerFactory.java:91)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$2.apply(ZincScalaCompilerFactory.java:88)
        at com.typesafe.zinc.Cache.get(Cache.scala:41)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.createCompiler(ZincScalaCompilerFactory.java:88)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.access$100(ZincScalaCompilerFactory.java:49)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$1.create(ZincScalaCompilerFactory.java:77)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory$1.create(ZincScalaCompilerFactory.java:73)
        at org.gradle.internal.SystemProperties.withSystemProperty(SystemProperties.java:127)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory.createParallelSafeCompiler(ZincScalaCompilerFactory.java:73)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:64)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:52)
        at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by theangrydev** [comment]
I fixed this by updating to the latest revision of `org.scala-lang:scala-library:2.11.12`

**Comment by rdblue** [comment]
I just hit this problem as well. Updating to 2.11.12 didn't work (plus, the version from Spark is 2.11.8). What worked for me was using Java 8 instead of Java 11.

**Comment by ttang235** [comment]
I had the same problem. Changing from Java 13 to Java 8 also solved my problem. 
I use intellij and maven. When I only changed java version in intellij 'project structure', the problem persisted. After I changed JAVA_HOME, and 'java -version' command showed 'java version "1.8.0_241"', the problem went away.

**Comment by eed3si9n** [comment]
Are you all hitting this problem using Gradle?

I should note that sbt launcher works around this issue by copying `rt.jar` to some directory and specifying `-Dscala.ext.dirs`. See https://github.com/sbt/sbt-launcher-package/pull/143

```
$ sbt -v
[process_args] java_version = '11'
[sbt_options] declare -a sbt_options='([0]="-Xms2048M" [1]="-Xmx2048M" [2]="-Xss2M")'
[copyRt] java9_rt = '/Users/eed3si9n/.sbt/0.13/java9-rt-ext-adoptopenjdk_11_0_4/rt.jar'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dscala.ext.dirs=/Users/eed3si9n/.sbt/0.13/java9-rt-ext-adoptopenjdk_11_0_4
-Xms2048M
-Xmx2048M
-Xss2M
-jar
/usr/local/Cellar/sbt/1.3.7/libexec/bin/sbt-launch.jar

$ ls ~/.sbt/0.13/java9-rt-ext-adoptopenjdk_11_0_4
rt.jar
```

**Comment by SethTisue** [comment]
it's fine and helpful to suggest downgrading to JDK 8 as one way to get this error message to go away, but I don't want anyone landing on this ticket to get the impression that JDK 11 or JDK 13 aren't supported by Scala, zinc, or sbt. they are supported _by current versions of Scala and zinc_ (for the Scala part, at present that means 2.11.12 or 2.12.10 or 2.13.1)

(I think that's the thought behind Eugene's question about gradle: that perhaps y'all are getting an outdated zinc version through gradle.)

**Comment by rthneha** [comment]
Yes changing java version from 11 to 8 in intellij helped.

**Comment by smrititaneja18** [comment]
> I just hit this problem as well. Updating to 2.11.12 didn't work (plus, the version from Spark is 2.11.8). What worked for me was using Java 8 instead of Java 11.

Hi,

How you changed Java 11 to java 8 at runtime?

**Comment by SethTisue** [comment]
@smrititaneja18 please use https://users.scala-lang.org, or other forums, for questions that aren't specific to the bug

**Comment by Alizeeshanhaider21** [comment]
> I fixed this by updating to the latest revision of `org. scala-lang:scala-library:2.11.12`

how to modify this? can you tell me the procedure? I also face the face issue and won't be able to resolve it. kindly guide me plz

**Comment by SethTisue** [comment]
@Alizeeshanhaider21 please use https://users.scala-lang.org, or another forum, for your question, which is not specific to this ticket

**Comment by paulpaul1076** [comment]
What the hell, I am literally getting with error with java 8.

**Comment by TobiasJuderjahn** [comment]
It's JAVA, lol.
